version: '3.8'

services:
  sogonDb:
    image: ankane/pgvector:latest
    container_name: sogonDb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgresData:/var/lib/postgresql/data
    restart: always