spring:
  application:
    name: sogonServer

  datasource:
    url: jdbc:postgresql://localhost:5432/sogon_db  
    username: sogon_dev
    password: sogon_pass    
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 로그인 토큰 설정
jwt:
  secret: VlwEyVlpkZpEQZnkkL8rVlwEyVlpkZpEQZnkkL8rVlwEyVlpkZpEQZnkkL8r
  expiration: 3600000 # 1 hour in milliseconds